basePath: /api/v1
definitions:
  models.Building:
    properties:
      city:
        type: string
      floors:
        type: integer
      id:
        type: integer
      name:
        type: string
      year:
        type: integer
    required:
    - city
    - floors
    - name
    - year
    type: object
  models.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Service for managing buildings
  title: Building Service API
  version: "1.0"
paths:
  /buildings:
    get:
      consumes:
      - application/json
      description: Get list of buildings
      parameters:
      - description: City
        in: query
        name: city
        type: string
      - description: Year built
        in: query
        name: year
        type: integer
      - description: Floors count
        in: query
        name: floors
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Building'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: List buildings
      tags:
      - buildings
    post:
      consumes:
      - application/json
      description: Create a new building
      parameters:
      - description: Building object
        in: body
        name: building
        required: true
        schema:
          $ref: '#/definitions/models.Building'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Building'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new building
      tags:
      - buildings
  /docs:
    get:
      description: Get Swagger API documentation
      produces:
      - text/html
      responses: {}
      summary: Swagger API documentation
      tags:
      - docs
swagger: "2.0"
